# Site Metadata
title: Ivan La Franca
description: Student Research Assistant at ECB

# Leave baseurl empty for user pages (username.github.io)
baseurl: ""
url: "https://ivanlafranca.github.io"

# Theme
theme: jekyll-theme-minimal

# Use a custom CSS file (placed at assets/css/style.css)
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      css: "assets/css/style.css"

# Options
show_downloads: true

