title: Ivan La Franca

logo: pic_LaFranca_a.jpg

description: Student Research assistant at ECB, DG-Research

# show_downloads: false

theme: chulapa-jekyll

<a href="yourfile.pdf" download>Download</a>

